# Generated by Django 2.1.5 on 2019-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.TextField(blank=True, db_column='Pos', null=True)),
                ('ht', models.TextField(blank=True, db_column='Ht', null=True)),
                ('wt', models.BigIntegerField(blank=True, db_column='Wt', null=True)),
                ('birth_date', models.DateTimeField(blank=True, db_column='Birth Date', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('exp', models.TextField(blank=True, db_column='Exp', null=True)),
                ('college', models.TextField(blank=True, db_column='College', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('year', models.BigIntegerField(blank=True, db_column='Year', null=True)),
            ],
            options={
                'db_table': 'Player Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryStats',
            fields=[
                ('player', models.TextField(blank=True, db_column='Player', primary_key=True, serialize=False)),
                ('tm', models.TextField(blank=True, db_column='Tm', null=True)),
                ('g', models.BigIntegerField(blank=True, db_column='G', null=True)),
                ('gs', models.BigIntegerField(blank=True, db_column='GS', null=True)),
                ('mp', models.BigIntegerField(blank=True, db_column='MP', null=True)),
                ('fg', models.BigIntegerField(blank=True, db_column='FG', null=True)),
                ('fga', models.BigIntegerField(blank=True, db_column='FGA', null=True)),
                ('fg_percent', models.DecimalField(blank=True, db_column='FG%', decimal_places=3, max_digits=4, null=True)),
                ('number_3p', models.BigIntegerField(blank=True, db_column='3P', null=True)),
                ('number_3pa', models.BigIntegerField(blank=True, db_column='3PA', null=True)),
                ('number_3p_field', models.DecimalField(blank=True, db_column='3P%', decimal_places=3, max_digits=4, null=True)),
                ('number_2p', models.BigIntegerField(blank=True, db_column='2P', null=True)),
                ('number_2pa', models.BigIntegerField(blank=True, db_column='2PA', null=True)),
                ('number_2p_field', models.DecimalField(blank=True, db_column='2P%', decimal_places=3, max_digits=4, null=True)),
                ('efg_field', models.DecimalField(blank=True, db_column='eFG%', decimal_places=3, max_digits=4, null=True)),
                ('ft', models.BigIntegerField(blank=True, db_column='FT', null=True)),
                ('fta', models.BigIntegerField(blank=True, db_column='FTA', null=True)),
                ('ft_field', models.DecimalField(blank=True, db_column='FT%', decimal_places=3, max_digits=4, null=True)),
                ('orb', models.BigIntegerField(blank=True, db_column='ORB', null=True)),
                ('drb', models.BigIntegerField(blank=True, db_column='DRB', null=True)),
                ('trb', models.BigIntegerField(blank=True, db_column='TRB', null=True)),
                ('ast', models.BigIntegerField(blank=True, db_column='AST', null=True)),
                ('stl', models.BigIntegerField(blank=True, db_column='STL', null=True)),
                ('blk', models.BigIntegerField(blank=True, db_column='BLK', null=True)),
                ('tov', models.BigIntegerField(blank=True, db_column='TOV', null=True)),
                ('pf', models.BigIntegerField(blank=True, db_column='PF', null=True)),
                ('pts', models.BigIntegerField(blank=True, db_column='PTS', null=True)),
                ('year', models.BigIntegerField(blank=True, db_column='Year', null=True)),
            ],
            options={
                'db_table': 'Summary Stats',
                'managed': False,
            },
        ),
    ]
