# Generated by Django 2.1.5 on 2019-03-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('player', models.TextField(blank=True, db_column='Player', primary_key=True, serialize=False)),
                ('tm', models.TextField(blank=True, db_column='Tm', null=True)),
                ('number_2018_19', models.BigIntegerField(blank=True, db_column='2018-19', null=True)),
                ('number_2019_20', models.BigIntegerField(blank=True, db_column='2019-20', null=True)),
                ('number_2020_21', models.BigIntegerField(blank=True, db_column='2020-21', null=True)),
                ('number_2021_22', models.BigIntegerField(blank=True, db_column='2021-22', null=True)),
                ('number_2022_23', models.BigIntegerField(blank=True, db_column='2022-23', null=True)),
                ('number_2023_24', models.BigIntegerField(blank=True, db_column='2023-24', null=True)),
                ('signed_using', models.TextField(blank=True, db_column='Signed Using', null=True)),
                ('guaranteed', models.BigIntegerField(blank=True, db_column='Guaranteed', null=True)),
            ],
            options={
                'db_table': 'Contracts',
                'managed': False,
            },
        ),
    ]
